server:
  port: 8091
  servlet:
    context-path: /
spring:
  datasource:
    #如果使用高版本的数据库则添加cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/jt?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: hlj172532


#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.jt.mapper: debug

#标识图片上传的路径
file:
  #本地存储的根目录
  localDir: D:/CGB2103_JT/image
  #网络访问虚拟路径
  urlPath: http://image.jt.com
